definitions:
  ds.Star:
    properties:
      description:
        description: Описание звезды
        type: string
      discoveryDate:
        description: Дата открытия
        type: string
      distance:
        description: Расстояние до звезды
        format: float32
        type: number
      id:
        type: integer
      imageName:
        description: Имя изображения для Minio
        type: string
      magnitude:
        description: Светимость
        format: float32
        type: number
      mass:
        description: Масса
        format: float32
        type: number
      starType:
        description: Тип звезды
        type: string
      temperature:
        description: Температура
        type: integer
      title:
        description: Название
        type: string
    type: object
  ds.StarCart:
    properties:
      comment:
        type: string
      creator:
        allOf:
        - $ref: '#/definitions/ds.User'
        description: Связи
      creatorID:
        description: Теперь UUID!
        type: string
      dateCreate:
        type: string
      dateFinished:
        type: string
      dateFormed:
        type: string
      id:
        type: integer
      items:
        items:
          $ref: '#/definitions/ds.StarCartItem'
        type: array
      moderator:
        $ref: '#/definitions/ds.User'
      moderatorID:
        description: И moderator тоже UUID
        type: string
      priority:
        type: string
      status:
        type: string
    type: object
  ds.StarCartItem:
    properties:
      cartID:
        type: integer
      comment:
        type: string
      id:
        type: integer
      quantity:
        type: integer
      speed:
        description: скорость
        format: float32
        type: number
      star:
        $ref: '#/definitions/ds.Star'
      starCart:
        allOf:
        - $ref: '#/definitions/ds.StarCart'
        description: <<< игнорируем при миграции
      starID:
        type: integer
    type: object
  ds.User:
    properties:
      login:
        description: уникальный логин
        type: string
      password:
        type: string
      role:
        allOf:
        - $ref: '#/definitions/role.Role'
        description: 0 = Buyer
      uuid:
        description: UUID как primary key
        type: string
    type: object
  handler.LoginRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  handler.loginResp:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      token_type:
        type: string
    type: object
  handler.registerReq:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  handler.registerResp:
    properties:
      ok:
        type: boolean
    type: object
  role.Role:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-comments:
      Admin: "2"
      Buyer: "0"
      Manager: "1"
    x-enum-descriptions:
    - "0"
    - "1"
    - "2"
    x-enum-varnames:
    - Buyer
    - Manager
    - Admin
host: localhost:8080
info:
  contact: {}
  description: Backend для управления заявками и звездами (Лабораторная 4)
  title: StarCart API
  version: "1.0"
paths:
  /api/starcart:
    get:
      parameters:
      - description: Дата с
        in: query
        name: from
        type: string
      - description: Дата по
        in: query
        name: to
        type: string
      - description: Статус заявки
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Получить список заявок (StarCart)
      tags:
      - StarCart
  /api/starcart/{cartID}:
    delete:
      parameters:
      - description: ID заявки
        in: path
        name: cartID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Удалить заявку (логически)
      tags:
      - StarCart
    get:
      parameters:
      - description: ID заявки
        in: path
        name: cartID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Получить детали заявки
      tags:
      - StarCart
  /api/starcart/{cartID}/finish:
    put:
      parameters:
      - description: ID заявки
        in: path
        name: cartID
        required: true
        type: integer
      - description: complete или reject
        in: query
        name: action
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.StarCart'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Завершить заявку (одобрить/отклонить)
      tags:
      - StarCart
  /api/starcart/{cartID}/form:
    put:
      parameters:
      - description: ID заявки
        in: path
        name: cartID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.StarCart'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Сформировать заявку
      tags:
      - StarCart
  /api/starcart/{cartID}/item/{id}:
    put:
      consumes:
      - application/json
      description: Изменяет количество, комментарий или скорость для конкретного элемента
        в заявке
      parameters:
      - description: ID заявки
        in: path
        name: cartID
        required: true
        type: integer
      - description: ID элемента в заявке
        in: path
        name: id
        required: true
        type: integer
      - description: Данные для обновления
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/ds.StarCartItem'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Обновить элемент заявки (м-м связь)
      tags:
      - StarCartItem
  /api/starcart/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: ID заявки
        in: path
        name: id
        required: true
        type: integer
      - description: Список позиций
        in: body
        name: items
        required: true
        schema:
          items:
            $ref: '#/definitions/ds.StarCartItem'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Обновить позиции в заявке
      tags:
      - StarCart
  /api/starcart/add:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: ID звезды
        in: formData
        name: star_id
        required: true
        type: integer
      - description: Количество
        in: formData
        name: quantity
        required: true
        type: integer
      - description: Комментарий
        in: formData
        name: comment
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Добавить звезду в заявку
      tags:
      - StarCart
  /api/starcart/icon:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
      summary: Получить иконку корзины (draft-заявка)
      tags:
      - StarCart
  /api/starcart/item/{id}:
    delete:
      parameters:
      - description: ID позиции
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Удалить позицию из заявки
      tags:
      - StarCartItem
  /api/stars:
    get:
      consumes:
      - application/json
      parameters:
      - description: Поиск по названию
        in: query
        name: title
        type: string
      - description: Минимальное расстояние
        in: query
        name: distance_min
        type: number
      - description: Максимальное расстояние
        in: query
        name: distance_max
        type: number
      - description: Тип звезды
        in: query
        name: star_type
        type: string
      - description: Минимальная светимость
        in: query
        name: magnitude_min
        type: number
      - description: Максимальная светимость
        in: query
        name: magnitude_max
        type: number
      - description: Минимальная температура
        in: query
        name: temperature_min
        type: number
      - description: Максимальная температура
        in: query
        name: temperature_max
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ds.Star'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Получить список звёзд с фильтрацией
      tags:
      - Stars
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные звезды
        in: body
        name: star
        required: true
        schema:
          $ref: '#/definitions/ds.Star'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/ds.Star'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Создать новую звезду
      tags:
      - Stars
  /api/stars/{id}:
    delete:
      parameters:
      - description: ID звезды
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Удалить звезду
      tags:
      - Stars
    get:
      description: Возвращает информацию и ссылку на изображение
      parameters:
      - description: ID звезды
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить подробности о звезде
      tags:
      - Stars
    put:
      consumes:
      - application/json
      parameters:
      - description: ID звезды
        in: path
        name: id
        required: true
        type: integer
      - description: Данные звезды
        in: body
        name: star
        required: true
        schema:
          $ref: '#/definitions/ds.Star'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.Star'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Обновить данные звезды
      tags:
      - Stars
  /api/stars/{id}/image:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: ID звезды
        in: path
        name: id
        required: true
        type: integer
      - description: Файл изображения
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Загрузить изображение для звезды
      tags:
      - Stars
  /api/users/login:
    post:
      consumes:
      - application/json
      description: Логиним пользователя
      parameters:
      - description: Данные для входа
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/handler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.loginResp'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Вход пользователя
      tags:
      - Users
  /api/users/logout:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Выход пользователя
      tags:
      - Users
  /api/users/me:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Получить информацию о текущем пользователе
      tags:
      - Users
    put:
      consumes:
      - application/json
      parameters:
      - description: Новые данные
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/ds.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Обновить данные пользователя
      tags:
      - Users
  /api/users/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные пользователя
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.registerReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.registerResp'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Зарегистрировать нового пользователя
      tags:
      - Users
securityDefinitions:
  BearerAuth:
    description: 'JWT Authorization header using the Bearer scheme. Example: "Bearer
      {token}"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
